"""empty message

Revision ID: 429920e60afe
Revises: af5ec6282c66
Create Date: 2019-11-02 14:18:50.370215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429920e60afe'
down_revision = 'af5ec6282c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('hasImage', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'hasImage')
    # ### end Alembic commands ###
