"""followers

Revision ID: 454fcff3e19f
Revises: 13d3e14b706a
Create Date: 2019-07-09 17:55:08.968944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454fcff3e19f'
down_revision = '13d3e14b706a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
